### ISSUE TITLE
Add instructions for self-hosting to README

### ISSUE THREAD

**Issue by steezeburger** [pastebinrun/pastebinrun#661]
This is basically the perfect paste bin IMO, and I would love to run this on my own server. Some instructions for self-hosting would be great! Maybe even a Docker image!

I'll take a stab at both these things this weekend and will create a PR if successful!

**Comment by xfix** [comment]
This application is made of two components:

- the public part which is in this repository - a mostly normal Rocket application that uses PostgreSQL database.
- the sandboxing micro-service in https://github.com/pastebinrun/nix-based-sandbox. It expects `bwrap` and all necessary executables to be in `PATH`.

The service is deployed on NixOS, and the configuration looks as follows: https://github.com/xfix/xfix.pw/blob/master/configuration/services/pastebinrun/default.nix (public part), https://github.com/xfix/xfix.pw/blob/master/configuration/services/sandbox/default.nix (sandboxing micro-service). Getting the sandbox to run on anything other than NixOS is probably going to be a pain, as it was never designed to.

Long time ago, there was a Docker Compose file for development purposes, and I probably should reintroduce it. However, the caveat with it is that sandboxing does not work in Docker: https://github.com/containers/bubblewrap/issues/505, so it's not very useful for actually deploying this software.

This pastebin isn't really maintained anymore due to lack of interest from me.

**Comment by steezeburger** [comment]
Makes sense! I didn't even think about Docker and sandboxing. I'll just keep using your hosted version ^_^
